theme: minima
title: Rahib Amin | Product & Technology Leader
author:
  name: Rahib Amin
  email: rahib.amin@thoughtworks.com
description: Technical Product Manager & Cloud Architect specializing in platform strategy and digital transformation
social_links:
  github: rahibamin
  linkedin: rahib-amin
  twitter: rahibamin
show_excerpts: true
header_pages:
  - about.md
  - blog.md
  - contact.md
minima:
  skin: dark
  social_links:
    github: https://www.github.com/rahibas
    linkedin: https://www.linkedin.com/in/rahib-amin-2aa402149/

  date_format: "%b %-d, %Y"


