remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: time-machine
title: Rahib's Proffesional Vanity Page
author: Rahib Amin
description: This is a place where people can learn a bit about my proffessional expereince and context.


