theme: minima
title: Rahib Amin | Product & Technology Leader
author:
  name: Rahib Amin
  email: your.email@example.com
description: Technical Product Manager & Cloud Architect specializing in platform strategy and digital transformation
social_links:
  github: rahibamin
  linkedin: rahib-amin
  twitter: rahibamin
show_excerpts: true
header_pages:
  - about.md
  - blog.md
  - contact.md
minima:
  skin: dark


